#!/usr/bin/env python3
"""Regenerates zifra/src/Webinterface.h from the HTML sources in zifra/pages/.

Each page is gzipped (deterministically: level 9, zeroed mtime) into a
PROGMEM byte array that the firmware serves with Content-Encoding: gzip.
Run after editing a page:  python3 tools/web/gzip_pages.py
"""
import gzip
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAGES = [
    ("index.html", "MAIN_PAGE"),
    ("update.html", "UPDATE_PAGE"),
]


def to_array(name, raw):
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(gz), 12):
        chunk = ", ".join("0x%02x" % b for b in gz[i:i + 12])
        lines.append("  " + chunk + ",")
    body = "\n".join(lines)
    return (
        "// %d bytes gzipped from %d\n"
        "const uint8_t %s_GZ[] PROGMEM = {\n%s\n};\n"
        "constexpr size_t %s_GZ_LEN = sizeof(%s_GZ);\n"
        % (len(gz), len(raw), name, body, name, name)
    ), len(raw), len(gz)


def main():
    parts = [
        "#pragma once\n"
        "#ifndef ZIFRA_WEBINTERFACE_H\n"
        "#define ZIFRA_WEBINTERFACE_H\n\n"
        "// GENERATED by tools/web/gzip_pages.py from zifra/pages/*.html —\n"
        "// edit the HTML there and rerun the script; do not edit this file.\n"
        "// Served with Content-Encoding: gzip (webservice.h).\n"
    ]
    for fname, cname in PAGES:
        with open(os.path.join(ROOT, "zifra", "pages", fname), "rb") as f:
            raw = f.read()
        block, n_raw, n_gz = to_array(cname, raw)
        parts.append("\n// zifra/pages/" + fname + "\n" + block)
        print("%-12s %5d -> %4d bytes" % (fname, n_raw, n_gz))
    parts.append("\n#endif\n")
    out = os.path.join(ROOT, "zifra", "src", "Webinterface.h")
    with open(out, "w") as f:
        f.write("".join(parts))
    print("wrote", out)


if __name__ == "__main__":
    main()
