#!/usr/bin/env python3
"""Regenerates zifra/src/Webinterface.h: everything the clock serves itself.

  zifra/pages/index.html  -> MAIN_PAGE_GZ   (the app shell, {{version}} filled in)
  zifra/pages/update.html -> UPDATE_PAGE_GZ (fallback flasher page)
  web/v2 JS bundle        -> APP_JS_GZ      (same file list as js/javascript.php)
  web/v2 CSS bundle       -> APP_CSS_GZ     (same file list as css/style.php)

Each blob is gzipped deterministically (level 9, zeroed mtime) into a
PROGMEM byte array served with Content-Encoding: gzip. build.sh runs this
before every firmware build; run it by hand after editing a page or the
web app:  python3 tools/web/gzip_pages.py
"""
import gzip
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
WEB = os.path.join(ROOT, "web", "v2")


def read(path):
    with open(path, "rb") as f:
        return f.read()


def version():
    src = read(os.path.join(ROOT, "zifra", "src", "version.h")).decode()
    return re.search(r'ZIFRA_VERSION\s+"([^"]+)"', src).group(1)


def php_bundle(bundler):
    """Concatenates the files a PHP bundler lists, in its order."""
    src = read(bundler).decode()
    files = re.findall(r"'\./files/([^']+)'", src)
    base = os.path.dirname(bundler)
    return b"\n".join(read(os.path.join(base, "files", f)) for f in files) + b"\n"


def to_array(name, raw, origin):
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(gz), 12):
        lines.append("  " + ", ".join("0x%02x" % b for b in gz[i:i + 12]) + ",")
    return (
        "\n// %s\n// %d bytes gzipped from %d\n"
        "const uint8_t %s_GZ[] PROGMEM = {\n%s\n};\n"
        "constexpr size_t %s_GZ_LEN = sizeof(%s_GZ);\n"
        % (origin, len(gz), len(raw), name, "\n".join(lines), name, name)
    ), len(raw), len(gz)


def main():
    ver = version()
    index = read(os.path.join(ROOT, "zifra", "pages", "index.html"))
    index = index.replace(b"{{version}}", ver.encode())
    blobs = [
        ("MAIN_PAGE", index, "zifra/pages/index.html (v" + ver + ")"),
        ("UPDATE_PAGE", read(os.path.join(ROOT, "zifra", "pages", "update.html")),
         "zifra/pages/update.html"),
        ("APP_JS", php_bundle(os.path.join(WEB, "js", "javascript.php")),
         "web/v2/js bundle"),
        ("APP_CSS", php_bundle(os.path.join(WEB, "css", "style.php")),
         "web/v2/css bundle"),
    ]
    parts = [
        "#pragma once\n"
        "#ifndef ZIFRA_WEBINTERFACE_H\n"
        "#define ZIFRA_WEBINTERFACE_H\n\n"
        "// GENERATED by tools/web/gzip_pages.py from zifra/pages/ and web/v2 -\n"
        "// edit those and rerun the script; do not edit this file.\n"
        "// Served with Content-Encoding: gzip (webservice.h).\n"
    ]
    total = 0
    for name, raw, origin in blobs:
        block, n_raw, n_gz = to_array(name, raw, origin)
        parts.append(block)
        total += n_gz
        print("%-24s %6d -> %5d bytes" % (origin.split(" (")[0], n_raw, n_gz))
    parts.append("\n#endif\n")
    out = os.path.join(ROOT, "zifra", "src", "Webinterface.h")
    with open(out, "w") as f:
        f.write("".join(parts))
    print("total %d bytes of PROGMEM, wrote %s" % (total, os.path.relpath(out, ROOT)))


if __name__ == "__main__":
    main()
